### ISSUE TITLE
Review entire site for style consistency

### ISSUE THREAD

**Issue by ghost** [dglunz/dinner_dash#89]

**Comment by ghost** [comment]
Fix padding on menu item views

Use sprintf for prices to ensure $x.xx output - DONE

**Comment by AdamSmith910** [comment]
home page should probably have sign up next to log in at top right

**Comment by AdamSmith910** [comment]
when adding an address, shouldn't it redirect back to the user, not to the new address?

**Comment by ghost** [comment]
User page should list user's own data so they can edit it.

**Comment by ghost** [comment]
Check all back/show buttons for consistent behavior per Adam's earlier comment for addresses.  Applies to user data also.
